{"name": "Create pet with invalid status", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for CreatePetSchema\nstatus\n  Value error, Invalid status: invalid_status. Status must be one of ['available', 'pending', 'sold'] [type=value_error, input_value='invalid_status', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.8/v/value_error", "trace": "self = <tests.test_pet.test_create_pet.TestCreatePet object at 0x00000244A3A0E200>\nget_test_name = 'tests/test_pet/test_create_pet.py::TestCreatePet::test_create_pet_with_invalid_status (setup)'\n\n    @allure.title(\"Create pet with invalid status\")\n    def test_create_pet_with_invalid_status(self, get_test_name):\n        info = next(self.pet_generator.generate_pet(status=\"invalid_status\"))\n        data = self.pet_data.prepare_pet_json(info=info)\n        response = self.request.post(url=self.url.create_pet, data=data)\n        self.assertions.assert_status_code(\n            response=response,\n            expected_status_code=HTTPStatus.OK,\n            test_name=get_test_name\n        )\n>       self.validator.validate_response(response=response, model=CreatePetSchemas.create_pet)\n\ntests\\test_pet\\test_create_pet.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nsrc\\validator.py:18: in validate_response\n    raise ex\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, model = <class 'src.schemas.pet_response_schema.CreatePetSchema'>\n\n    @staticmethod\n    def validate_response(response: Response, model):\n        try:\n>           validation = model.model_validate_json(response.text)\nE           pydantic_core._pydantic_core.ValidationError: 1 validation error for CreatePetSchema\nE           status\nE             Value error, Invalid status: invalid_status. Status must be one of ['available', 'pending', 'sold'] [type=value_error, input_value='invalid_status', input_type=str]\nE               For further information visit https://errors.pydantic.dev/2.8/v/value_error\n\nsrc\\validator.py:13: ValidationError"}, "attachments": [{"name": "Request", "source": "dfabe264-3115-41dc-af9b-036b7dd4687d-attachment.json", "type": "application/json"}, {"name": "Response", "source": "b776e753-42db-4ce5-979e-1541a5fe0150-attachment.json", "type": "application/json"}, {"name": "log", "source": "73013d9d-1046-44b7-bf54-e5d064276cb9-attachment.txt", "type": "text/plain"}], "start": 1724067081864, "stop": 1724067082489, "uuid": "9f49fb89-c356-40df-ad6f-51c082f24346", "historyId": "e832090af80879b6cc923c197d84b7c8", "testCaseId": "e832090af80879b6cc923c197d84b7c8", "fullName": "tests.test_pet.test_create_pet.TestCreatePet#test_create_pet_with_invalid_status", "labels": [{"name": "epic", "value": "Testing create pet"}, {"name": "parentSuite", "value": "tests.test_pet"}, {"name": "suite", "value": "test_create_pet"}, {"name": "subSuite", "value": "TestCreatePet"}, {"name": "host", "value": "DESKTOP-7NMG6HA"}, {"name": "thread", "value": "8660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_pet.test_create_pet"}]}